apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller-broker
  namespace: data-platform
  labels:
    strimzi.io/cluster: data-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: ephemeral
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  jvmOptions:
    "-Xms": "128m"
    "-Xmx": "256m"
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: data-cluster
  namespace: data-platform
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.7.0
    metadataVersion: 3.7-IV4
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 64Mi
        limits:
          memory: 256Mi
    userOperator:
      resources:
        requests:
          memory: 64Mi
        limits:
          memory: 256Mi
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: eventos-financeiros
  namespace: data-platform
  labels:
    strimzi.io/cluster: data-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 104857600
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: events-dlq
  namespace: data-platform
  labels:
    strimzi.io/cluster: data-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 104857600
    cleanup.policy: delete
